### ISSUE TITLE
Reorganize visitor/mapper code

### ISSUE THREAD

**Issue by JonoYang** [aboutcode-org/purldb#283]
Currently we are putting code for the on-demand/priority queue in with the visitor code. It would be better if we separated the code. We should also decide which term we want to use for the on-demand/priority queue, since we use both currently. It is also worth considering if we want to merge the visitor and mapper code as well.

**Comment by pombredanne** [comment]
See also https://github.com/nexB/purldb/issues/521

**Comment by JonoYang** [comment]
The visitors and mappers have been merged into a single module named `miners`.
