### ISSUE TITLE
Analyze 1000 source and binary packages with d2d pipeline

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/purldb#421]
I would like to analyze roughly 1000 source and binary packages with d2d pipeline to evaluate how it performs.
Some packages to consider could include xz-utils/liblzma, Apache httrace, and a slice of popular packages. 

We should have a report on this to integrate in the documentation and as a blog post, including any possible CVEs/discrepancy detected in the process.

The run of a 1000 packages will need to be called either from the purlcli + some custom script or a complete custom script:
- [x] We will use this https://github.com/nexB/purldb/issues/420
- [x] We will then script call using this CLI based on a list of PURLs to run them all
- [x] We are creating a list of packages. A good starting list is with the projects used in purl2sym. I drafted this for a start: https://docs.google.com/spreadsheets/d/1FzZjPsR8V0M55b76p9RZ9V4rTRrxLglJ/edit#gid=1581254170
and we can use a CSV later on.

**Comment by pombredanne** [comment]
A good starting list would be the projects used in purl2sym. I drafted this for a start: https://docs.google.com/spreadsheets/d/1FzZjPsR8V0M55b76p9RZ9V4rTRrxLglJ/edit#gid=1581254170
and we can use a CSV later on.

**Comment by pombredanne** [comment]
For reference, Fedora is fairly helpful there. Here are some exmaples:

jq
- https://archive.fedoraproject.org/pub/fedora/linux/releases/40/Everything/x86_64/debug/tree/Packages/j/jq-debuginfo-1.7.1-4.fc40.x86_64.rpm#to
- https://archive.fedoraproject.org/pub/fedora/linux/releases/40/Everything/x86_64/debug/tree/Packages/j/jq-debugsource-1.7.1-4.fc40.x86_64.rpm#from
- https://archive.fedoraproject.org/pub/fedora/linux/releases/40/Everything/source/tree/Packages/j/jq-1.7.1-4.fc40.src.rpm#from

Another one:

- https://archive.fedoraproject.org/pub/fedora/linux/releases/40/Everything/x86_64/debug/tree/Packages/l/libxml2-debuginfo-2.12.6-1.fc40.x86_64.rpm

For Go:
- https://github.com/containers/podman/releases/tag/v5.0.3 is a good one with source and binaries

**Comment by TG1999** [comment]
[from_to_urls.txt](https://github.com/user-attachments/files/15546195/from_to_urls.txt)

Got this with all pairs of URLs to run d2d on.

**Comment by pombredanne** [comment]
This has been completed
