### ISSUE TITLE
Migrate repository to aboutcode-org

### ISSUE THREAD

**Issue by chinyeungli** [aboutcode-org/purldb#517]
Procedures:

- [x] Announce on Gitter/Element, in a specific channel if available, to notify of the org migration process including the scheduled start time and the expected completion time.
- [x] Follow the following procedures instruction for the org migration process
  - [x] 1. Transfer the nexB repo to the aboutcode-org organization from Settings -> Danger Zone -> Transfer ownership
  - [x] 2. Set up CI for that repo on Azure Devops
    * Log into the nexB organization on Azure Devops
    * Go to the project that was moved
    * On the left hand menu, click on Pipelines, and then delete the existing pipeline
    * On the same page, click New pipeline, and then click Github, then select the repo that was transferred to aboutcode-org
    * Complete adding the pipeline
- [x] Announce on Gitter/Element, in a specific channel if available, to notify the completion of the org migration.
- [x] Update org-level permissions: Check org-level permissions for the source repo and update the repo-level permissions on the migrated repo
- [x] Check if there are any old references with the previous org (documentation, reference links) that need to be updated.
- [x] Push a new release about the org change with the updated references

**Comment by chinyeungli** [comment]
@pombredanne Can you explain a bit more on how to perform
 Update org-level permissions: Check org-level permissions for the source repo and update the repo-level permissions on the migrated repo

In addition, if there is no references with the previous org that need to be updated, do we still push a new release?

**Comment by mjherzog** [comment]
@chinyeungli For the Gitter notifications, please announce all in aboutcode-org/discuss and also in the module-specific channel is there is is one. I see fetchcode, scancode, scancode-workbench and dejacode as the relevant module-level channels.

**Comment by pombredanne** [comment]
@chinyeungli re:
> Update org-level permissions: Check org-level permissions for the source repo and update the repo-level permissions on the migrated repo

We need to check and recreate the permissions we have in the source org in the target org. This can be done after the migration and announce. Folks impacted may complain soon enough otherwise.

> In addition, if there is no references with the previous org that need to be updated, do we still push a new release?

No need to, but I would be surprised there is no URL at all.

**Comment by chinyeungli** [comment]
repo migrated.
