### ISSUE TITLE
Dead link in documentaion

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/purldb#540]
From https://aboutcode.readthedocs.io/projects/PURLdb/en/latest/how-to-guides/symbols_and_strings.html
The link to "installation" is a dead link:
![Screenshot 2024-10-19 at 11-05-14 Collect symbols and strings from a PURL aka  purl2sym — PurlDB documentation](https://github.com/user-attachments/assets/b19680bb-a7d8-4eda-a476-565df9fc4b35)

https://aboutcode.readthedocs.io/projects/PURLdb/en/latest/purldb/overview.html#installation

**Comment by ajithpkumar18** [comment]
Hi, Can I work on this issue?

**Comment by JonoYang** [comment]
@ajithpkumar18 Go for it!

**Comment by alok1304** [comment]
@JonoYang Can I work on it.
